services:
  poc-server:
    build: ./poc-server
    container_name: secure_server
    volumes:
      - ./poc-server/data:/app/data
    networks:
      - secure_net
    ports:
      - "5000:5000"

  client_a:
    build: ./poc-client
    container_name: client_a
    volumes:
      - ./poc-client/keys/a:/app/keys
    networks:
      - secure_net
    depends_on:
      - poc-server
    stdin_open: true
    tty: true

  client_b:
    build: ./poc-client
    container_name: client_b
    volumes:
      - ./poc-client/keys/b:/app/keys
    networks:
      - secure_net
    depends_on:
      - poc-server
    stdin_open: true
    tty: true

networks:
  secure_net:
    driver: bridge