services:
  server:
    build: ./server
    container_name: secure_server
    volumes:
      - ./server/data:/app/data
    networks:
      - secure_net
    ports:
      - "5000:5000"

  client_a:
    build: ./client
    container_name: client_a
    volumes:
      - ./client/keys/a:/app/keys
    networks:
      - secure_net
    depends_on:
      - server
    stdin_open: true
    tty: true

  client_b:
    build: ./client
    container_name: client_b
    volumes:
      - ./client/keys/b:/app/keys
    networks:
      - secure_net
    depends_on:
      - server
    stdin_open: true
    tty: true

networks:
  secure_net:
    driver: bridge