services:
  poc-server:
    build: ./poc-server
    container_name: secure_server
    volumes:
      - ./poc-server/data:/app/data
      - ./logs:/app/logs
    networks:
      - secure_net
    ports:
      - "5000:5000"

  client_a:
    build: ./poc-client
    container_name: client_a
    volumes:
      - ./poc-client/keys/a:/app/keys
      - ./authority/keys:/app/authority_keys:ro
      - ./logs:/app/logs
    networks:
      - secure_net
    depends_on:
      - poc-server
    stdin_open: true
    tty: true

  client_b:
    build: ./poc-client
    container_name: client_b
    volumes:
      - ./poc-client/keys/b:/app/keys
      - ./authority/keys:/app/authority_keys:ro
      - ./logs:/app/logs
    networks:
      - secure_net
    depends_on:
      - poc-server
    stdin_open: true
    tty: true

  authority:
    build: ./authority
    container_name: authority
    volumes:
      - ./authority/keys:/app/keys
      - ./authority/state:/app/data/state
      - ./authority/intercepts:/app/intercepts
      - ./poc-server/data/messages.json:/app/data/messages.json:ro
      - ./logs:/app/logs
    networks:
      - secure_net
    depends_on:
      - poc-server
      
networks:
  secure_net:
    driver: bridge
